"""Service abstraction shared by SimulatedBenchService and RealBenchService.

The web layer (`api/{control,recording,data,ws}.py`) only needs the methods
listed here; both backends implement the same surface so the `lifespan`
hook can swap them based on `PICKUP_EDS_BRIDGE_URL`.

`Protocol` is used (not `ABC`) to avoid forcing a class-hierarchy and to
keep the simulator drop-in compatible without inheritance.
"""
from __future__ import annotations

import asyncio
from pathlib import Path
from typing import Any, Protocol

from pickup_eds.schemas import AppState, DatasetSummary, ScpiLogEntry


class BenchServiceProtocol(Protocol):
    """The Bench surface the FastAPI handlers depend on."""

    @property
    def data_dir(self) -> Path: ...

    # Lifecycle
    async def start(self) -> None: ...
    async def stop(self) -> None: ...

    # State
    async def snapshot_state(self) -> AppState: ...
    def add_state_watcher(self) -> asyncio.Queue[dict[str, object]]: ...
    def remove_state_watcher(self, queue: asyncio.Queue[dict[str, object]]) -> None: ...

    # 6514 control toggles
    async def set_function(self, func: str) -> AppState: ...
    async def set_range(self, range_value: float) -> AppState: ...
    async def set_zero_check(self, on: bool) -> AppState: ...
    async def set_zero_correct(self, on: bool) -> AppState: ...

    # SCPI passthrough
    async def scpi_log(self) -> list[ScpiLogEntry]: ...
    async def send_scpi(self, command: str) -> ScpiLogEntry: ...

    # Recording
    async def start_recording(self, label: str, duration_s: float | None) -> AppState: ...
    async def stop_recording(self) -> tuple[AppState, DatasetSummary | None]: ...

    # Datasets
    async def datasets(self) -> list[DatasetSummary]: ...
    async def preview_dataset(self, dataset_id: str) -> dict[str, object] | None: ...
    async def get_dataset(self, dataset_id: str) -> DatasetSummary | None: ...

    # Live stream frame for /ws/stream (decimated, JSON-friendly).
    async def stream_frame(self) -> dict[str, object]: ...

    # DAQ task control (Phase 2 additions; simulator implements as no-op
    # equivalents that mutate display-only state).
    async def daq_run(self, config: dict[str, Any]) -> AppState: ...
    async def daq_pause(self) -> AppState: ...
    async def daq_stop(self) -> AppState: ...
    async def daq_single(self, config: dict[str, Any]) -> AppState: ...

    # Analog-output free-run (Phase 2 only; HW-sync deferred to 2.5).
    async def ao_start(self, config: dict[str, Any]) -> AppState: ...
    async def ao_stop(self) -> AppState: ...
